name: Deploy to UAT

on:
  push:
    branches:
      - uat

  pull_request:
    branches:
      - uat

jobs:
  validate-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all tags and branches
        run: git fetch --all --tags

      - name: Get the branch name
        id: get_branch_name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          else
            BRANCH_NAME="${{ github.ref_name }}"
          fi
          echo "Branch Name: $BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Get the latest commit hash from the source branch
        id: get_commit
        run: |
          echo "Fetching commit hash from branch: ${{ env.branch_name }}"
          COMMIT_HASH=$(git rev-parse origin/${{ env.branch_name }}) || exit 1
          echo "Commit Hash: $COMMIT_HASH"
          echo "commit_hash=$COMMIT_HASH" >> $GITHUB_ENV

      - name: Check if commit has already been deployed
        run: |
          if git log origin/gh-pages --pretty=format:"%H" | grep -q "${{ env.commit_hash }}"; then
            echo "Commit ${{ env.commit_hash }} has already been deployed. Exiting."
            exit 0
          fi

      - name: Validate commit exists in QA history
        run: |
          QA_COMMITS=$(git log origin/qa --pretty=format:"%H")
          echo "QA Commits: $QA_COMMITS"
          
          if echo "$QA_COMMITS" | grep -q "${{ env.commit_hash }}"; then
            echo "Commit ${{ env.commit_hash }} exists in QA history."
          else
            echo "Commit ${{ env.commit_hash }} does not exist in QA history. Exiting."
            exit 1
          fi

      - name: Deploy to UAT
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: uat.sitio.com