name: Deploy to DEV with Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies using Yarn
        run: yarn install  # Aquí cambiamos npm por yarn

      - name: Run lint
        run: yarn lint  # Cambiamos npm por yarn

      - name: Run tests
        run: yarn test --coverage  # Cambiamos npm por yarn

      - name: Build the application
        run: yarn build  # Cambiamos npm por yarn

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: dev.sitio.com