name: Sync master with prod

on:
  pull_request:
    branches:
      - prod
    types: [closed]  # Solo cuando el pull request está cerrado (es decir, mergeado)

jobs:
  sync-master:
    if: ${{ github.event.pull_request.merged == true }}  # Aseguramos que el PR fue mergeado
    runs-on: ubuntu-latest
    steps:
      - name: Checkout prod branch
        uses: actions/checkout@v4
        with:
          ref: prod

      - name: Sync master with prod
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.REPO_ACTOR }}"
          git checkout main
          git merge prod
          git push origin main

