name: Sync master with prod

on:
  push:
    branches:
      - prod

jobs:
  sync-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout prod branch
        uses: actions/checkout@v4
        with:
          ref: prod

      - name: Sync master with prod
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.REPO_ACTOR }}"
          git checkout master
          git merge prod
          git push origin master


