name: Sync master with prod

on:
  workflow_run:
    workflows: ["Deploy to Production"]
    types:
      - completed

jobs:
  sync-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout prod branch
        uses: actions/checkout@v4
        with:
          ref: prod

      - name: Checkout master branch
        run: |
          git fetch origin master
          git checkout master

      - name: Sync master with prod
        run: |
          git merge prod
          git push origin master