name: Tag Approved QA Commit

on:
  workflow_run:
    workflows: ["Deploy to QA"]
    types:
      - completed

jobs:
  tag-commit:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get the branch name
        id: vars
        run: |
          BRANCH_NAME="${{ github.event.workflow_run.head_branch }}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Get the latest commit hash from QA
        id: get_commit
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          echo "commit_hash=$COMMIT_HASH" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          TAG_NAME="${{ env.branch_name }}-qa-approved-${{ env.commit_hash }}"
          echo "Creating tag: $TAG_NAME"
          git tag -a -- "$TAG_NAME" -m "QA approved $BRANCH_NAME on commit ${{ env.commit_hash }}"
          git push origin --tags