name: Tag Approved QA Commit

on:
  workflow_run:
    workflows: ["Deploy to QA"]
    types:
      - completed

jobs:
  tag-commit:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Git user
      run: git config --global user.email "${{ secrets.EMAIL }}" && git config --global
        user.name "${{ secrets.REPO_ACTOR }}"
    - id: vars
      name: Get the branch name
      run: BRANCH_NAME=$(echo "${GITHUB_HEAD_REF}") && echo "branch_name=$BRANCH_NAME"
        >> $GITHUB_ENV
    - id: get_commit
      name: Get the latest commit hash from QA
      run: COMMIT_HASH=$(git rev-parse HEAD) && echo "commit_hash=$COMMIT_HASH" >>
        $GITHUB_ENV
    - name: Create and push tag
      run: TAG_NAME="${{ env.branch_name }}-qa-approved-${{ env.commit_hash }}" &&
        git tag -a "$TAG_NAME" -m "QA approved $BRANCH_NAME on commit ${{ env.commit_hash
        }}" && git push origin "$TAG_NAME"