name: Tag Approved QA Commit

on:
  workflow_run:
    workflows: ["Deploy to QA"]
    types:
      - completed

jobs:
  tag-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --all --tags

      - name: Get commit hash
        id: get_commit
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          echo "Commit Hash: $COMMIT_HASH"
          echo "commit_hash=$COMMIT_HASH" >> $GITHUB_ENV

      - name: Create Tag Name
        id: create_tag
        run: |
          TAG_NAME="qa-approved-${{ env.commit_hash }}"
          echo "Tag Name: $TAG_NAME"
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists. Skipping tag creation."
            exit 0
          else
            echo "Tag $TAG_NAME does not exist. Proceeding with creation."
          fi

      - name: Create and Push Tag
        if: ${{ steps.check_tag.outcome == 'success' }}
        run: |
          git tag -a "$TAG_NAME" -m "QA approved commit ${{ env.commit_hash }}"
          git push origin "$TAG_NAME"
